### ISSUE TITLE
Add XMPP JID to keymasters

### ISSUE THREAD

**Issue by the-metalgamer** [spacedirectory/schema#4]
Add a new property to the keymasters for specifying XMPP jid.

The key name should xmpp or jid and the type should be a string.

**Comment by dbrgn** [comment]
+1 on this.

Note that the `contact` key already contains a `jabber` key. We should probably use consistent naming.

I'd propose renaming the `contact.jabber` field to `contact.xmpp` and to add `contact.keymasters.xmpp`.
